
import { Car, NewsPost, InboxMessage, Testimonial, AboutData } from './types';

export const INITIAL_CARS: Car[] = [
  {
    id: '1',
    name: 'Avanza 1.5 G CVT',
    brand: 'Toyota',
    price: 275000000,
    year: 2023,
    engine: '1.5L Dual VVT-i',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'MPV sejuta umat dengan tampilan baru yang lebih modern. Penggerak roda depan (FWD) membuat kabin lebih luas dan konsumsi BBM lebih irit. Cocok untuk keluarga.',
    is_featured: true,
    mileage: 15000,
    fuel_type: 'Bensin',
    body_type: 'MPV',
    color: 'Purplish Silver',
    interior_color: 'Hitam / Coklat',
    tax_date: 'Mei 2025',
    previous_owners: 1,
    service_history: 'Lengkap (Auto2000)',
    condition: 'Bekas',
    location: 'Jakarta Selatan',
    seats: 7,
    plate_number: 'B 2910 TZU (Genap)',
    gallery: [
      'https://images.unsplash.com/photo-1626322969986-e9d6efc25227?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=1200'
    ]
  },
  {
    id: '2',
    name: 'Brio RS Urbanite',
    brand: 'Honda',
    price: 240000000,
    year: 2023,
    engine: '1.2L i-VTEC',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&q=80&w=1200',
    description: 'City car terlaris di Indonesia. Lincah, irit, dan sporty. Varian RS Urbanite dengan bodykit agresif, cocok untuk anak muda atau mobilitas harian di Jakarta.',
    is_featured: true,
    mileage: 8000,
    fuel_type: 'Bensin',
    body_type: 'Hatchback',
    color: 'Phoenix Orange Pearl',
    interior_color: 'Hitam dengan Aksen Oranye',
    tax_date: 'Agustus 2024',
    previous_owners: 1,
    service_history: 'Lengkap',
    condition: 'Bekas',
    location: 'Jakarta Barat',
    seats: 5,
    plate_number: 'B 1123 UKL (Ganjil)',
    gallery: [
        'https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&q=80&w=1200',
        'https://images.unsplash.com/photo-1533473359331-0135ef1bcfb0?auto=format&fit=crop&q=80&w=1200'
    ]
  },
  {
    id: '3',
    name: 'Xpander Ultimate',
    brand: 'Mitsubishi',
    price: 295000000,
    year: 2022,
    engine: '1.5L MIVEC',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1625055082126-78b7b209c25f?auto=format&fit=crop&q=80&w=1200',
    description: 'MPV dengan suspensi paling nyaman di kelasnya. Desain Dynamic Shield yang gagah dan interior mewah dengan soft touch. AC double blower sangat dingin.',
    is_featured: true,
    mileage: 25000,
    fuel_type: 'Bensin',
    body_type: 'MPV',
    color: 'Quartz White Pearl',
    interior_color: 'Beige',
    tax_date: 'Januari 2025',
    previous_owners: 1,
    service_history: 'Lengkap (Mitsubishi Lautan)',
    condition: 'Bekas',
    location: 'Tangerang',
    seats: 7,
    plate_number: 'B 8899 EXP (Ganjil)'
  },
  {
    id: '4',
    name: 'Kijang Innova Reborn 2.4 V',
    brand: 'Toyota',
    price: 415000000,
    year: 2021,
    engine: '2.4L Diesel Turbo',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=1200',
    description: 'Mobil keluarga paling tangguh dan dicari. Mesin diesel 2GD yang bertenaga dan badak. Kabin hening, fitur lengkap, captain seat opsional. Favorit travel.',
    is_featured: false,
    mileage: 45000,
    fuel_type: 'Diesel',
    body_type: 'MPV',
    color: 'Attitude Black',
    interior_color: 'Hitam Kayu',
    tax_date: 'Desember 2024',
    previous_owners: 1,
    service_history: 'Rutin Auto2000',
    condition: 'Bekas',
    location: 'Jakarta Selatan',
    seats: 7,
    plate_number: 'B 1998 KJG (Genap)'
  },
  {
    id: '5',
    name: 'HR-V SE CVT',
    brand: 'Honda',
    price: 385000000,
    year: 2023,
    engine: '1.5L DOHC i-VTEC',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&q=80&w=1200',
    description: 'Compact SUV yang stylish dengan fitur Honda Sensing lengkap. Panoramic glass roof memberikan kesan mewah dan luas. Sangat populer di kalangan eksekutif muda.',
    is_featured: false,
    mileage: 12000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Sand Khaki Pearl',
    interior_color: 'Hitam Kulit',
    tax_date: 'Maret 2025',
    previous_owners: 1,
    service_history: 'Lengkap',
    condition: 'Bekas',
    location: 'Bekasi',
    seats: 5,
    plate_number: 'B 2233 HRV (Ganjil)'
  },
  {
    id: '6',
    name: 'Sigra 1.2 R DLX',
    brand: 'Daihatsu',
    price: 165000000,
    year: 2024,
    engine: '1.2L Dual VVT-i',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=1200',
    description: 'LCGC 7-seater paling ekonomis. Solusi tepat untuk taksi online atau keluarga muda. Perawatan murah, sparepart melimpah, dan sangat irit BBM.',
    is_featured: false,
    mileage: 5000,
    fuel_type: 'Bensin',
    body_type: 'MPV',
    color: 'Orange Metallic',
    interior_color: 'Hitam / Abu',
    tax_date: 'Juni 2025',
    previous_owners: 1,
    service_history: 'Lengkap',
    condition: 'Bekas',
    location: 'Depok',
    seats: 7,
    plate_number: 'B 4567 SGR (Ganjil)'
  },
  {
    id: '7',
    name: 'Ertiga Hybrid GX',
    brand: 'Suzuki',
    price: 260000000,
    year: 2023,
    engine: '1.5L Smart Hybrid',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1658428236750-68195449089f?auto=format&fit=crop&q=80&w=1200',
    description: 'LMPV Hybrid pertama di kelasnya. Teknologi Smart Hybrid membuat konsumsi bahan bakar lebih efisien dan start-stop halus. Fitur Cruise Control tersedia.',
    is_featured: false,
    mileage: 18000,
    fuel_type: 'Hybrid',
    body_type: 'MPV',
    color: 'Magma Grey',
    interior_color: 'Hitam Wood Panel',
    tax_date: 'Oktober 2024',
    previous_owners: 1,
    service_history: 'Lengkap',
    condition: 'Bekas',
    location: 'Jakarta Timur',
    seats: 7,
    plate_number: 'B 1010 ERT (Genap)'
  },
  {
    id: '8',
    name: 'Rush 1.5 S TRD Sportivo',
    brand: 'Toyota',
    price: 255000000,
    year: 2021,
    engine: '1.5L Dual VVT-i',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1627454819213-17727e4b52af?auto=format&fit=crop&q=80&w=1200',
    description: 'LSUV RWD yang tangguh di segala medan jalanan Indonesia. Ground clearance tinggi, muat 7 penumpang. Desain sporty khas TRD.',
    is_featured: false,
    mileage: 38000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'White',
    interior_color: 'Hitam',
    tax_date: 'Juli 2024',
    previous_owners: 1,
    service_history: 'Lengkap',
    condition: 'Bekas',
    location: 'Bogor',
    seats: 7,
    plate_number: 'F 1234 RSH (Genap)'
  },
  {
    id: '9',
    name: 'Fortuner 2.4 VRZ TRD',
    brand: 'Toyota',
    price: 650000000,
    year: 2022,
    engine: '2.4L Diesel Turbo',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV tangguh dengan mesin diesel bertenaga. Cocok untuk off-road dan perjalanan jauh.',
    is_featured: false,
    mileage: 30000,
    fuel_type: 'Diesel',
    body_type: 'SUV',
    color: 'Barcelona Red',
    interior_color: 'Hitam Kulit',
    tax_date: 'November 2024',
    previous_owners: 1,
    service_history: 'Lengkap Auto2000',
    condition: 'Bekas',
    location: 'Jakarta Pusat',
    seats: 7,
    plate_number: 'B 5678 FTN (Ganjil)'
  },
  {
    id: '10',
    name: 'Civic Type R',
    brand: 'Honda',
    price: 850000000,
    year: 2023,
    engine: '2.0L Turbo VTEC',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Sedan sport dengan performa tinggi. Mesin turbocharged yang responsif.',
    is_featured: true,
    mileage: 5000,
    fuel_type: 'Bensin',
    body_type: 'Sedan',
    color: 'Rallye Red',
    interior_color: 'Merah Kulit',
    tax_date: 'September 2025',
    previous_owners: 1,
    service_history: 'Lengkap',
    condition: 'Bekas',
    location: 'Jakarta Utara',
    seats: 4,
    plate_number: 'B 9999 CVC (Genap)'
  },
  {
    id: '11',
    name: 'Pajero Sport Dakar Ultimate',
    brand: 'Mitsubishi',
    price: 750000000,
    year: 2023,
    engine: '2.4L Diesel Turbo',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV off-road legendaris dengan fitur keselamatan lengkap.',
    is_featured: false,
    mileage: 20000,
    fuel_type: 'Diesel',
    body_type: 'SUV',
    color: 'White Diamond',
    interior_color: 'Coklat Kulit',
    tax_date: 'April 2025',
    previous_owners: 1,
    service_history: 'Lengkap Mitsubishi',
    condition: 'Bekas',
    location: 'Tangerang Selatan',
    seats: 7,
    plate_number: 'B 7777 PJS (Ganjil)'
  },
  {
    id: '12',
    name: 'XL7 Beta Hybrid',
    brand: 'Suzuki',
    price: 280000000,
    year: 2023,
    engine: '1.5L Smart Hybrid',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV crossover hybrid yang efisien dan modern.',
    is_featured: false,
    mileage: 15000,
    fuel_type: 'Hybrid',
    body_type: 'SUV',
    color: 'Prime Grey',
    interior_color: 'Hitam',
    tax_date: 'Februari 2025',
    previous_owners: 1,
    service_history: 'Lengkap',
    condition: 'Bekas',
    location: 'Bekasi',
    seats: 7,
    plate_number: 'B 3333 XL7 (Genap)'
  },
  {
    id: '13',
    name: 'Terios 1.5 X',
    brand: 'Daihatsu',
    price: 210000000,
    year: 2023,
    engine: '1.5L Dual VVT-i',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV kompak yang cocok untuk keluarga dengan konsumsi bahan bakar rendah.',
    is_featured: false,
    mileage: 25000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Icy White',
    interior_color: 'Abu-abu',
    tax_date: 'Juli 2024',
    previous_owners: 1,
    service_history: 'Lengkap Daihatsu',
    condition: 'Bekas',
    location: 'Depok',
    seats: 7,
    plate_number: 'B 4444 TRS (Ganjil)'
  },
  {
    id: '14',
    name: 'Livina 1.5 VE',
    brand: 'Nissan',
    price: 235000000,
    year: 2022,
    engine: '1.5L Dual VVT',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'MPV serbaguna dengan interior yang luas dan fitur keselamatan.',
    is_featured: false,
    mileage: 35000,
    fuel_type: 'Bensin',
    body_type: 'MPV',
    color: 'Brilliant Silver',
    interior_color: 'Hitam',
    tax_date: 'Desember 2024',
    previous_owners: 1,
    service_history: 'Lengkap Nissan',
    condition: 'Bekas',
    location: 'Bogor',
    seats: 7,
    plate_number: 'B 5555 LVN (Genap)'
  },
  {
    id: '15',
    name: 'Creta Prestige',
    brand: 'Hyundai',
    price: 340000000,
    year: 2023,
    engine: '1.5L Turbo GDi',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV crossover dengan desain modern dan teknologi canggih.',
    is_featured: false,
    mileage: 18000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Phantom Black',
    interior_color: 'Hitam Kulit',
    tax_date: 'Agustus 2025',
    previous_owners: 1,
    service_history: 'Lengkap Hyundai',
    condition: 'Bekas',
    location: 'Jakarta Timur',
    seats: 5,
    plate_number: 'B 6666 CRT (Ganjil)'
  },
  {
    id: '16',
    name: 'Seltos EX',
    brand: 'Kia',
    price: 350000000,
    year: 2023,
    engine: '1.4L Turbo GDi',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV stylish dengan fitur keselamatan lengkap dan interior premium.',
    is_featured: false,
    mileage: 12000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Gravity Grey',
    interior_color: 'Hitam',
    tax_date: 'Oktober 2025',
    previous_owners: 1,
    service_history: 'Lengkap Kia',
    condition: 'Bekas',
    location: 'Jakarta Barat',
    seats: 5,
    plate_number: 'B 7777 SLT (Genap)'
  },
  {
    id: '17',
    name: 'Vios 1.5 E CVT',
    brand: 'Toyota',
    price: 245000000,
    year: 2023,
    engine: '1.5L Dual VVT-i',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'Sedan kompak yang irit bahan bakar dan nyaman untuk penggunaan sehari-hari.',
    is_featured: false,
    mileage: 22000,
    fuel_type: 'Bensin',
    body_type: 'Sedan',
    color: 'Silver Metallic',
    interior_color: 'Abu-abu',
    tax_date: 'Januari 2025',
    previous_owners: 1,
    service_history: 'Lengkap Auto2000',
    condition: 'Bekas',
    location: 'Tangerang',
    seats: 5,
    plate_number: 'B 8888 VIO (Ganjil)'
  },
  {
    id: '18',
    name: 'Jazz RS CVT',
    brand: 'Honda',
    price: 270000000,
    year: 2023,
    engine: '1.5L i-VTEC',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Hatchback sporty dengan desain agresif dan performa yang responsif.',
    is_featured: false,
    mileage: 16000,
    fuel_type: 'Bensin',
    body_type: 'Hatchback',
    color: 'Lunar Silver',
    interior_color: 'Hitam Sport',
    tax_date: 'Maret 2025',
    previous_owners: 1,
    service_history: 'Lengkap Honda',
    condition: 'Bekas',
    location: 'Bekasi',
    seats: 5,
    plate_number: 'B 9999 JZZ (Genap)'
  },
  {
    id: '19',
    name: 'Xpander Exceed CVT',
    brand: 'Mitsubishi',
    price: 310000000,
    year: 2023,
    engine: '1.5L MIVEC',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'MPV dengan suspensi nyaman dan fitur keselamatan canggih.',
    is_featured: false,
    mileage: 14000,
    fuel_type: 'Bensin',
    body_type: 'MPV',
    color: 'Jet Black Mica',
    interior_color: 'Beige',
    tax_date: 'Mei 2025',
    previous_owners: 1,
    service_history: 'Lengkap Mitsubishi',
    condition: 'Bekas',
    location: 'Jakarta Selatan',
    seats: 7,
    plate_number: 'B 1111 XPD (Ganjil)'
  },
  {
    id: '20',
    name: 'Ertiga GL MT',
    brand: 'Suzuki',
    price: 225000000,
    year: 2022,
    engine: '1.5L K15B',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'MPV kompak dengan konsumsi bahan bakar efisien.',
    is_featured: false,
    mileage: 28000,
    fuel_type: 'Bensin',
    body_type: 'MPV',
    color: 'Pearl Arctic White',
    interior_color: 'Hitam',
    tax_date: 'Juni 2024',
    previous_owners: 1,
    service_history: 'Lengkap Suzuki',
    condition: 'Bekas',
    location: 'Depok',
    seats: 7,
    plate_number: 'B 2222 ERT (Genap)'
  },
  {
    id: '21',
    name: 'Xenia 1.3 R MT',
    brand: 'Daihatsu',
    price: 170000000,
    year: 2021,
    engine: '1.3L Dual VVT-i',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'MPV andal dengan perawatan mudah dan sparepart terjangkau.',
    is_featured: false,
    mileage: 45000,
    fuel_type: 'Bensin',
    body_type: 'MPV',
    color: 'Icy White',
    interior_color: 'Abu-abu',
    tax_date: 'November 2024',
    previous_owners: 2,
    service_history: 'Rutin Daihatsu',
    condition: 'Bekas',
    location: 'Bogor',
    seats: 7,
    plate_number: 'B 3333 XEN (Ganjil)'
  },
  {
    id: '22',
    name: 'Terra 2.0L 4x2 AT',
    brand: 'Nissan',
    price: 420000000,
    year: 2023,
    engine: '2.0L Twin Turbo Diesel',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV tangguh dengan mesin diesel bertenaga untuk berbagai medan.',
    is_featured: false,
    mileage: 25000,
    fuel_type: 'Diesel',
    body_type: 'SUV',
    color: 'Gun Metallic',
    interior_color: 'Hitam Kulit',
    tax_date: 'September 2025',
    previous_owners: 1,
    service_history: 'Lengkap Nissan',
    condition: 'Bekas',
    location: 'Tangerang Selatan',
    seats: 7,
    plate_number: 'B 4444 TER (Genap)'
  },
  {
    id: '23',
    name: 'Tucson GLS',
    brand: 'Hyundai',
    price: 380000000,
    year: 2022,
    engine: '2.0L Nu MPI',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV mid-size dengan interior luas dan fitur canggih.',
    is_featured: false,
    mileage: 32000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Starry Night',
    interior_color: 'Coklat Kulit',
    tax_date: 'April 2025',
    previous_owners: 1,
    service_history: 'Lengkap Hyundai',
    condition: 'Bekas',
    location: 'Jakarta Utara',
    seats: 5,
    plate_number: 'B 5555 TCS (Ganjil)'
  },
  {
    id: '24',
    name: 'Sportage LX',
    brand: 'Kia',
    price: 360000000,
    year: 2023,
    engine: '2.0L Nu MPI',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV stylish dengan desain aerodinamis dan teknologi modern.',
    is_featured: false,
    mileage: 19000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Snow White Pearl',
    interior_color: 'Hitam',
    tax_date: 'Juli 2025',
    previous_owners: 1,
    service_history: 'Lengkap Kia',
    condition: 'Bekas',
    location: 'Bekasi',
    seats: 5,
    plate_number: 'B 6666 SPT (Genap)'
  },
  {
    id: '25',
    name: 'Camry 2.5 V',
    brand: 'Toyota',
    price: 680000000,
    year: 2023,
    engine: '2.5L Dual VVT-i',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'Sedan mewah dengan performa halus dan interior premium.',
    is_featured: true,
    mileage: 8000,
    fuel_type: 'Bensin',
    body_type: 'Sedan',
    color: 'Radiant Red',
    interior_color: 'Kulit Beige',
    tax_date: 'Desember 2025',
    previous_owners: 1,
    service_history: 'Lengkap Auto2000',
    condition: 'Bekas',
    location: 'Jakarta Pusat',
    seats: 5,
    plate_number: 'B 7777 CMY (Ganjil)'
  },
  {
    id: '26',
    name: 'Accord 2.0 Turbo',
    brand: 'Honda',
    price: 720000000,
    year: 2023,
    engine: '2.0L Turbo VTEC',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Sedan premium dengan teknologi keselamatan Honda Sensing.',
    is_featured: false,
    mileage: 10000,
    fuel_type: 'Bensin',
    body_type: 'Sedan',
    color: 'Platinum White',
    interior_color: 'Hitam Kulit',
    tax_date: 'Februari 2025',
    previous_owners: 1,
    service_history: 'Lengkap Honda',
    condition: 'Bekas',
    location: 'Jakarta Selatan',
    seats: 5,
    plate_number: 'B 8888 ACD (Genap)'
  },
  {
    id: '27',
    name: 'Outlander PHEV',
    brand: 'Mitsubishi',
    price: 850000000,
    year: 2023,
    engine: '2.4L Hybrid',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV hybrid dengan jangkauan listrik yang luas.',
    is_featured: false,
    mileage: 5000,
    fuel_type: 'Hybrid',
    body_type: 'SUV',
    color: 'Red Diamond',
    interior_color: 'Putih',
    tax_date: 'Agustus 2025',
    previous_owners: 1,
    service_history: 'Lengkap Mitsubishi',
    condition: 'Bekas',
    location: 'Tangerang',
    seats: 7,
    plate_number: 'B 9999 OTL (Ganjil)'
  },
  {
    id: '28',
    name: 'Jimny Sierra',
    brand: 'Suzuki',
    price: 320000000,
    year: 2023,
    engine: '1.5L K15B',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV off-road kompak yang tangguh di berbagai kondisi.',
    is_featured: false,
    mileage: 12000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Kinetic Yellow',
    interior_color: 'Hitam',
    tax_date: 'Oktober 2025',
    previous_owners: 1,
    service_history: 'Lengkap Suzuki',
    condition: 'Bekas',
    location: 'Depok',
    seats: 4,
    plate_number: 'B 1112 JMY (Genap)'
  },
  {
    id: '29',
    name: 'Sirion 1.3 MT',
    brand: 'Daihatsu',
    price: 130000000,
    year: 2020,
    engine: '1.3L Dual VVT-i',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Hatchback ekonomis dengan perawatan murah.',
    is_featured: false,
    mileage: 50000,
    fuel_type: 'Bensin',
    body_type: 'Hatchback',
    color: 'Silver',
    interior_color: 'Abu-abu',
    tax_date: 'Januari 2024',
    previous_owners: 2,
    service_history: 'Rutin',
    condition: 'Bekas',
    location: 'Bogor',
    seats: 5,
    plate_number: 'B 2223 SRI (Ganjil)'
  },
  {
    id: '30',
    name: 'March 1.2 MT',
    brand: 'Nissan',
    price: 150000000,
    year: 2021,
    engine: '1.2L Dual VVT',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'City car lincah untuk mobilitas harian.',
    is_featured: false,
    mileage: 40000,
    fuel_type: 'Bensin',
    body_type: 'Hatchback',
    color: 'Red',
    interior_color: 'Hitam',
    tax_date: 'Maret 2024',
    previous_owners: 1,
    service_history: 'Lengkap Nissan',
    condition: 'Bekas',
    location: 'Depok',
    seats: 5,
    plate_number: 'B 3334 MRC (Genap)'
  },
  {
    id: '31',
    name: 'Santa Fe',
    brand: 'Hyundai',
    price: 500000000,
    year: 2022,
    engine: '2.2L Diesel',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV premium dengan interior mewah.',
    is_featured: false,
    mileage: 25000,
    fuel_type: 'Diesel',
    body_type: 'SUV',
    color: 'White',
    interior_color: 'Kulit Hitam',
    tax_date: 'November 2025',
    previous_owners: 1,
    service_history: 'Lengkap Hyundai',
    condition: 'Bekas',
    location: 'Jakarta Pusat',
    seats: 7,
    plate_number: 'B 4445 STF (Ganjil)'
  },
  {
    id: '32',
    name: 'Sorento',
    brand: 'Kia',
    price: 480000000,
    year: 2023,
    engine: '2.2L Diesel',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV keluarga dengan ruang kargo besar.',
    is_featured: false,
    mileage: 18000,
    fuel_type: 'Diesel',
    body_type: 'SUV',
    color: 'Black',
    interior_color: 'Kulit Coklat',
    tax_date: 'Desember 2025',
    previous_owners: 1,
    service_history: 'Lengkap Kia',
    condition: 'Bekas',
    location: 'Tangerang',
    seats: 7,
    plate_number: 'B 5556 SRT (Genap)'
  },
  {
    id: '33',
    name: 'Crown 2.0 Hybrid',
    brand: 'Toyota',
    price: 900000000,
    year: 2023,
    engine: '2.0L Hybrid',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'Sedan hybrid mewah dengan teknologi canggih.',
    is_featured: true,
    mileage: 7000,
    fuel_type: 'Hybrid',
    body_type: 'Sedan',
    color: 'Pearl White',
    interior_color: 'Kulit Beige',
    tax_date: 'Oktober 2025',
    previous_owners: 1,
    service_history: 'Lengkap Auto2000',
    condition: 'Bekas',
    location: 'Jakarta Selatan',
    seats: 5,
    plate_number: 'B 6667 CRN (Ganjil)'
  },
  {
    id: '34',
    name: 'NSX',
    brand: 'Honda',
    price: 2500000000,
    year: 2023,
    engine: '3.5L V6 Hybrid',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'Supercar hybrid dengan performa luar biasa.',
    is_featured: true,
    mileage: 3000,
    fuel_type: 'Hybrid',
    body_type: 'Coupe',
    color: 'Nouvelle Blue Pearl',
    interior_color: 'Kulit Merah',
    tax_date: 'September 2025',
    previous_owners: 1,
    service_history: 'Lengkap Honda',
    condition: 'Bekas',
    location: 'Jakarta Pusat',
    seats: 2,
    plate_number: 'B 7778 NSX (Genap)'
  },
  {
    id: '35',
    name: 'Lancer Evolution X',
    brand: 'Mitsubishi',
    price: 600000000,
    year: 2020,
    engine: '2.0L Turbo',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Sedan sport legendaris dengan mesin turbo.',
    is_featured: false,
    mileage: 35000,
    fuel_type: 'Bensin',
    body_type: 'Sedan',
    color: 'Rally Red',
    interior_color: 'Hitam',
    tax_date: 'Juli 2024',
    previous_owners: 1,
    service_history: 'Lengkap Mitsubishi',
    condition: 'Bekas',
    location: 'Bekasi',
    seats: 5,
    plate_number: 'B 8889 EVO (Ganjil)'
  },
  {
    id: '36',
    name: 'Swift Sport',
    brand: 'Suzuki',
    price: 250000000,
    year: 2022,
    engine: '1.4L Turbo',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'Hatchback sporty dengan handling tajam.',
    is_featured: false,
    mileage: 20000,
    fuel_type: 'Bensin',
    body_type: 'Hatchback',
    color: 'Yellow',
    interior_color: 'Hitam',
    tax_date: 'Agustus 2024',
    previous_owners: 1,
    service_history: 'Lengkap Suzuki',
    condition: 'Bekas',
    location: 'Depok',
    seats: 4,
    plate_number: 'B 9990 SFT (Genap)'
  },
  {
    id: '37',
    name: 'Luxio 1.5 MT',
    brand: 'Daihatsu',
    price: 180000000,
    year: 2021,
    engine: '1.5L Dual VVT-i',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'MPV komersial dengan kapasitas muat besar.',
    is_featured: false,
    mileage: 60000,
    fuel_type: 'Bensin',
    body_type: 'MPV',
    color: 'White',
    interior_color: 'Abu-abu',
    tax_date: 'Februari 2024',
    previous_owners: 2,
    service_history: 'Rutin Daihatsu',
    condition: 'Bekas',
    location: 'Bogor',
    seats: 10,
    plate_number: 'B 1113 LUX (Ganjil)'
  },
  {
    id: '38',
    name: 'Juke 1.6 Turbo',
    brand: 'Nissan',
    price: 300000000,
    year: 2022,
    engine: '1.6L Turbo',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV crossover unik dengan desain futuristik.',
    is_featured: false,
    mileage: 22000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Orange',
    interior_color: 'Hitam',
    tax_date: 'April 2025',
    previous_owners: 1,
    service_history: 'Lengkap Nissan',
    condition: 'Bekas',
    location: 'Tangerang',
    seats: 5,
    plate_number: 'B 2224 JUK (Genap)'
  },
  {
    id: '39',
    name: 'Palisade',
    brand: 'Hyundai',
    price: 700000000,
    year: 2023,
    engine: '3.5L V6',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV besar dengan kapasitas 8 penumpang.',
    is_featured: false,
    mileage: 15000,
    fuel_type: 'Bensin',
    body_type: 'SUV',
    color: 'Silver',
    interior_color: 'Kulit Hitam',
    tax_date: 'Juni 2025',
    previous_owners: 1,
    service_history: 'Lengkap Hyundai',
    condition: 'Bekas',
    location: 'Jakarta Utara',
    seats: 8,
    plate_number: 'B 3335 PLS (Ganjil)'
  },
  {
    id: '40',
    name: 'Carnival',
    brand: 'Kia',
    price: 650000000,
    year: 2023,
    engine: '2.2L Diesel',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'MPV premium dengan konfigurasi kursi fleksibel.',
    is_featured: false,
    mileage: 12000,
    fuel_type: 'Diesel',
    body_type: 'MPV',
    color: 'White',
    interior_color: 'Kulit Abu',
    tax_date: 'Agustus 2025',
    previous_owners: 1,
    service_history: 'Lengkap Kia',
    condition: 'Bekas',
    location: 'Bekasi',
    seats: 9,
    plate_number: 'B 4446 CRN (Genap)'
  },
  {
    id: '41',
    name: 'Prius 1.8 Hybrid',
    brand: 'Toyota',
    price: 450000000,
    year: 2023,
    engine: '1.8L Hybrid',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Sedan hybrid irit bahan bakar.',
    is_featured: false,
    mileage: 10000,
    fuel_type: 'Hybrid',
    body_type: 'Sedan',
    color: 'Blue',
    interior_color: 'Abu-abu',
    tax_date: 'November 2025',
    previous_owners: 1,
    service_history: 'Lengkap Auto2000',
    condition: 'Bekas',
    location: 'Depok',
    seats: 5,
    plate_number: 'B 5557 PRI (Ganjil)'
  },
  {
    id: '42',
    name: 'Insight Hybrid',
    brand: 'Honda',
    price: 400000000,
    year: 2022,
    engine: '1.5L Hybrid',
    transmission: 'CVT',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'Hatchback hybrid dengan efisiensi tinggi.',
    is_featured: false,
    mileage: 18000,
    fuel_type: 'Hybrid',
    body_type: 'Hatchback',
    color: 'Silver',
    interior_color: 'Hitam',
    tax_date: 'Desember 2024',
    previous_owners: 1,
    service_history: 'Lengkap Honda',
    condition: 'Bekas',
    location: 'Bogor',
    seats: 5,
    plate_number: 'B 6668 INS (Genap)'
  },
  {
    id: '43',
    name: 'i-MiEV',
    brand: 'Mitsubishi',
    price: 350000000,
    year: 2021,
    engine: 'Listrik',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'Mobil listrik kompak untuk penggunaan perkotaan.',
    is_featured: false,
    mileage: 25000,
    fuel_type: 'Listrik',
    body_type: 'Hatchback',
    color: 'White',
    interior_color: 'Abu-abu',
    tax_date: 'Januari 2025',
    previous_owners: 1,
    service_history: 'Lengkap Mitsubishi',
    condition: 'Bekas',
    location: 'Tangerang',
    seats: 4,
    plate_number: 'B 7779 IMI (Ganjil)'
  },
  {
    id: '44',
    name: 'Wagon R Stingray',
    brand: 'Suzuki',
    price: 160000000,
    year: 2020,
    engine: '1.0L',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Kei car mungil dengan konsumsi bahan bakar minimal.',
    is_featured: false,
    mileage: 30000,
    fuel_type: 'Bensin',
    body_type: 'Hatchback',
    color: 'Blue',
    interior_color: 'Hitam',
    tax_date: 'Maret 2024',
    previous_owners: 2,
    service_history: 'Rutin',
    condition: 'Bekas',
    location: 'Jakarta Barat',
    seats: 4,
    plate_number: 'B 8880 WGR (Genap)'
  },
  {
    id: '45',
    name: 'Mira 0.66L',
    brand: 'Daihatsu',
    price: 100000000,
    year: 2019,
    engine: '0.66L',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'Kei car entry-level dengan biaya operasional rendah.',
    is_featured: false,
    mileage: 40000,
    fuel_type: 'Bensin',
    body_type: 'Hatchback',
    color: 'Pink',
    interior_color: 'Abu-abu',
    tax_date: 'April 2024',
    previous_owners: 3,
    service_history: 'Rutin Daihatsu',
    condition: 'Bekas',
    location: 'Depok',
    seats: 4,
    plate_number: 'B 9991 MIR (Ganjil)'
  },
  {
    id: '46',
    name: 'Leaf',
    brand: 'Nissan',
    price: 500000000,
    year: 2022,
    engine: 'Listrik',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'Mobil listrik dengan jangkauan yang baik.',
    is_featured: false,
    mileage: 15000,
    fuel_type: 'Listrik',
    body_type: 'Hatchback',
    color: 'Red',
    interior_color: 'Hitam',
    tax_date: 'Juli 2025',
    previous_owners: 1,
    service_history: 'Lengkap Nissan',
    condition: 'Bekas',
    location: 'Jakarta Timur',
    seats: 5,
    plate_number: 'B 1114 LEF (Genap)'
  },
  {
    id: '47',
    name: 'Ioniq Hybrid',
    brand: 'Hyundai',
    price: 420000000,
    year: 2023,
    engine: '1.6L Hybrid',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Sedan hybrid dengan desain aerodinamis.',
    is_featured: false,
    mileage: 12000,
    fuel_type: 'Hybrid',
    body_type: 'Sedan',
    color: 'White',
    interior_color: 'Abu-abu',
    tax_date: 'September 2025',
    previous_owners: 1,
    service_history: 'Lengkap Hyundai',
    condition: 'Bekas',
    location: 'Bekasi',
    seats: 5,
    plate_number: 'B 2225 ION (Ganjil)'
  },
  {
    id: '48',
    name: 'Niro Hybrid',
    brand: 'Kia',
    price: 430000000,
    year: 2023,
    engine: '1.6L Hybrid',
    transmission: 'Otomatis',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&q=80&w=1200',
    description: 'SUV crossover hybrid dengan efisiensi tinggi.',
    is_featured: false,
    mileage: 10000,
    fuel_type: 'Hybrid',
    body_type: 'SUV',
    color: 'Blue',
    interior_color: 'Hitam',
    tax_date: 'Oktober 2025',
    previous_owners: 1,
    service_history: 'Lengkap Kia',
    condition: 'Bekas',
    location: 'Tangerang Selatan',
    seats: 5,
    plate_number: 'B 3336 NIR (Genap)'
  },
  {
    id: '49',
    name: '86',
    brand: 'Toyota',
    price: 550000000,
    year: 2022,
    engine: '2.0L Boxer',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1549399735-cef2e2c3f638?auto=format&fit=crop&q=80&w=1200',
    description: 'Coupe sporty dengan mesin boxer yang responsif.',
    is_featured: false,
    mileage: 8000,
    fuel_type: 'Bensin',
    body_type: 'Coupe',
    color: 'Red',
    interior_color: 'Hitam',
    tax_date: 'November 2025',
    previous_owners: 1,
    service_history: 'Lengkap Auto2000',
    condition: 'Bekas',
    location: 'Jakarta Pusat',
    seats: 4,
    plate_number: 'B 4447 E86 (Ganjil)'
  },
  {
    id: '50',
    name: 'S2000',
    brand: 'Honda',
    price: 800000000,
    year: 2020,
    engine: '2.0L VTEC',
    transmission: 'Manual',
    image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1200',
    description: 'Roadster ikonik dengan mesin high-revving.',
    is_featured: false,
    mileage: 20000,
    fuel_type: 'Bensin',
    body_type: 'Convertible',
    color: 'Yellow',
    interior_color: 'Hitam',
    tax_date: 'Desember 2024',
    previous_owners: 1,
    service_history: 'Lengkap Honda',
    condition: 'Bekas',
    location: 'Jakarta Selatan',
    seats: 2,
    plate_number: 'B 5558 S2K (Genap)'
  }
];

export const INITIAL_NEWS: NewsPost[] = [
  {
    id: '1',
    title: 'Tips Merawat Transmisi CVT Agar Awet',
    excerpt: 'Pengguna mobil modern wajib tahu, ini cara mengemudi yang benar agar sabuk baja CVT tidak cepat putus.',
    content: 'Transmisi CVT semakin populer di Indonesia...',
    date: '2024-05-15',
    author: 'Renova Bengkel',
    image: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?auto=format&fit=crop&q=80&w=800'
  },
  {
    id: '2',
    title: 'Perbandingan Konsumsi BBM: Avanza vs Xpander',
    excerpt: 'Kami menguji dua MPV terlaris ini dalam rute dalam kota Jakarta yang macet dan tol luar kota.',
    content: 'Dalam pengujian rute kombinasi sejauh 200km...',
    date: '2024-05-12',
    author: 'Renova Test Drive',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=800'
  }
];

export const INITIAL_INBOX: InboxMessage[] = [
  {
    id: '1',
    type: 'general',
    name: 'Budi Santoso',
    email: 'budi.s@gmail.com',
    subject: 'Simulasi Kredit Innova',
    message: 'Halo admin, bisa tolong kirimkan simulasi kredit untuk Innova Reborn diesel DP 50 juta tenor 4 tahun?',
    date: '2024-05-14',
    isRead: false
  },
  {
    id: '2',
    type: 'test-drive',
    name: 'Diana Putri',
    email: 'diana.p@gmail.com',
    phone: '081234567890',
    carName: 'HR-V SE CVT',
    bookingDate: '2024-05-20',
    subject: 'Booking Test Drive: HR-V SE CVT',
    message: 'Saya ingin mencoba fitur Honda Sensing di jalan tol.',
    date: '2024-05-16',
    isRead: false
  }
];

export const INITIAL_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Wijaya',
    role: 'Pembeli HR-V SE',
    rating: 5,
    comment: 'Pelayanan sangat ramah, proses kredit dibantu sampai goal. Mobilnya juga sangat mulus seperti baru. Recommended showroom!',
    date: '2024-05-10',
    isVisible: true
  },
  {
    id: '2',
    name: 'Denny Sumargo',
    role: 'Pembeli Fortuner',
    rating: 5,
    comment: 'Unit sangat terawat, jujur soal kondisi mobil. Harga bersaing dengan showroom lain di Jakarta Selatan.',
    date: '2024-04-22',
    isVisible: true
  },
  {
    id: '3',
    name: 'Jessica Tanoe',
    role: 'Trade-in Brio',
    rating: 4,
    comment: 'Proses trade-in cepat, harga taksiran mobil lama saya cukup tinggi. Terima kasih Renova!',
    date: '2024-03-15',
    isVisible: true
  }
];

export const INITIAL_ABOUT: AboutData = {
  description: "Selamat datang di Renova Mobil, destinasi utama Anda untuk menemukan kendaraan berkualitas tinggi dengan harga yang kompetitif. Sejak didirikan pada tahun 1998, kami telah mendedikasikan diri untuk mengubah pengalaman membeli mobil bekas menjadi sesuatu yang menyenangkan, transparan, dan terpercaya.\n\nDi Renova, setiap unit kendaraan melewati proses inspeksi 150 titik yang ketat oleh teknisi bersertifikat kami. Kami tidak hanya menjual mobil; kami menjual ketenangan pikiran. Komitmen kami terhadap kualitas memastikan bahwa setiap mobil yang keluar dari showroom kami siap untuk menemani perjalanan Anda tanpa rasa khawatir.",
  mission: "Menjadi showroom mobil terpercaya nomor satu di Indonesia yang mengutamakan kepuasan pelanggan melalui integritas, kualitas unit terbaik, dan layanan purna jual yang unggul.",
  gallery: [
    "https://images.unsplash.com/photo-1562141961-b5d1855d7f30?auto=format&fit=crop&q=80&w=1200",
    "https://images.unsplash.com/photo-1485291571150-772bcfc10da5?auto=format&fit=crop&q=80&w=1200",
    "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&q=80&w=1200",
    "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=1200"
  ]
};

export const BRANDS = ['Semua', 'Toyota', 'Honda', 'Daihatsu', 'Mitsubishi', 'Suzuki', 'Nissan', 'Wuling', 'Mazda'];
